### ISSUE TITLE
turtles

### ISSUE THREAD

**Issue by eepykate** [6gk/turtles#1]
## TODO

 - [ ] [bongko](https://cdn.discordapp.com/emojis/685897493833056339.gif)
 - [x] burgker
 - [ ] chigken
 - [ ] cyborgk
 - [x] disgko
 - [ ] tippingk (fedora) ~~+ a pun~~
 - [ ] gklitch (glitch effect over a regular turtle? glitch effect over hagker?  stripes of other turtle emoji?  hat having horizontal lines missing?)
 - [x] gkod (long hair, white shawl, glow filter)
 - [ ] gkrandfather (boomer)
 - [ ] gkosthugk    [reminder to remind mander]
 - [ ] [gkrave](https://cdn.discordapp.com/emojis/823951946859282472.gif)
 - [ ] gkrave (the ded person kind)
 - [x] handsome jagk
 - [ ] hongk    (honk, goose)
 - [x] magkician
 - [ ] mouse    (scroll wheel / buttons on shell) (needs a pun)
 - [ ] mlgk
 - [ ] pegk     (bird)
 - [ ] plugk    (electrical plug)
 - [ ] quagk    (quack, duck)
 - [x] quigk    (flash?)  (Thanks dnl!)
 - [x] rogket man
 - [x] sherlogk with _the hat:tm:_
 - [ ] smugk
 - [ ] snagk (sausage (snag) or a snack)
 - [x] snagke (snake) longk
 - [ ] longk skateboard
 - [ ] strangke (doctor strange, but idk sounds a bit like strangle)
 - [x] tangk (motherfucking army tank, blastoise)
 - [ ] wigked (witch? ronald weasley?)
 - [ ] sirius blagk
 - [ ] orangke
 - [ ] gkenie
 - [ ] tagkeout
 - [ ] boomerangk
 - [ ] spagketti
 - [x] gkamer (Mario hat)
 - [ ] longkun
 - [x] bootlegk [new turtle with cowboy hat]
 - [ ] hologkram https://www.freepik.com/blog/photography-create-a-hologram-effect/
 - [ ] amerigkan with chips
 - [ ] insomniagk (suggested by monke0192, no idea what it'll look like)
 - [ ] sleepingk
 - [ ] new turtle at old turtle angle

**Comment by dnl32** [comment]
i may start working on quigk, tho i will need to learn how to do like a speed effect. would be also cool to turn it into gif one day but i don't know anything about gif editing and stuff

**Comment by eepykate** [comment]
Making gifs is possible with olive (export as mov -> quicktime or whatever -> advanced -> argb colourspace -> use ffmpeg or something to turn from transparent mov to transparent gif)

There's also gimp, but that's painful with a lot of frames (though you can use xdotool to semi-script it, and it has a built-in thing but I've never used that)

**Comment by elkowar** [comment]
idea: 
gun-left neck bidirectional-turtlebody neck gun-right

inspiration: 
![image](https://user-images.githubusercontent.com/5300871/123948508-c1d73280-d9a1-11eb-922b-4790d3034e88.png)

**Comment by monke0192** [comment]
## bad fedora pun incoming
tippingk

**Comment by eepykate** [comment]
lmao that's actually surprisingly decent, @MonkeOoOo
